spring.datasource.url=jdbc:mysql://sakura.proxy.rlwy.net:13773/railway
spring.datasource.username=root
spring.datasource.password=KecJijlgWddmzJsBjvEwCwGzHOcBvKeQ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
